version: 0.2

env:
  shell: bash
  variables:
    CDK_VERSION: "1.130.0"

phases:
  install:
    runtime-versions:
      python: 3.7
      java: 11
  build:
    commands:
      # Compile Java modules
      - "mvn clean install -Dmaven.test.skip=true"
      # Install Python dependencies
      - "(cd dog-expert-python && pip3 install -t . -r requirements.txt)"
      # Prepare docker container
      - "cp dog-expert-discord/target/dog-expert-discord-1.0-SNAPSHOT.jar dog-expert-docker/service.jar"
      - "mkdir -p dog-expert-docker/python"
      - "cp -r dog-expert-python dog-expert-docker/python"
      # Synthesize application/service CDK stacks for application deployment
      - "mkdir -p generated/cloud-assembly"
      - "(cd dog-expert-cdk && cdk synth -o ../../generated/cloud-assembly)"
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud_assembly"
  base-directory: "generated/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"
    -
